### ISSUE TITLE
Circular allocation in ModelLoader and LightningModule

### ISSUE THREAD

**Issue by chiragraman** [gabinsane/multimodal-vae-comparison#2]
Hi, 

Wanted to separate the issues so they are easily addressable as units. Following up from the previous issue about naming the LightningModule, I also noticed that the Trainer is allocated in the ModelLoader:

https://github.com/gabinsane/multimodal-vae-comparison/blob/056cf7efb12e6aa7bd6ec0d76f29b4a3921ba683/multimodal_compare/models/trainer.py#L21

while the ModelLoader is allocated in the LightningModule

https://github.com/gabinsane/multimodal-vae-comparison/blob/056cf7efb12e6aa7bd6ec0d76f29b4a3921ba683/multimodal_compare/models/trainer.py#L99

This seems a little problematic. It seems like the ModelLoader methods can simply be static or class methods, since they don't seem to be maintaining any state. 

Overall it's unclear to me where the model is actually instantiated; this is probably a separate issue, but just thought of asking it as a clarification. 

Thanks for putting this repo together!

**Comment by gabinsane** [comment]
Hi,
we removed the ModelLoader class in the last commit (the original intention was to have model instantiation outside MultimodalVAE to make it accessible for inference, but I later learned that the pl module is necessary for checkpoint loading anyway). 

As for the model instantiation - in the updated version, it happens in get_model() (https://github.com/gabinsane/multimodal-vae-comparison/blob/main/multimodal_compare/models/trainer.py), line 56 for individual VAEs and l. 57 for the multimodal VAE. 

Please let me know if that answered your question or if anything else needs to be clarified.

Thanks!

**Comment by chiragraman** [comment]
Hi hi,

> but I later learned that the pl module is necessary for checkpoint loading anyway

Actually, separating model initialization outside the lightning module is indeed possible. (I personally quite like that design and agree with your original choice.) See here: [https://pytorch-lightning.readthedocs.io/en/latest/common/checkpointing_basic.html?highlight=checkpoint#save-hyperparameters](https://pytorch-lightning.readthedocs.io/en/latest/common/checkpointing_basic.html?highlight=checkpoint#save-hyperparameters)

You can directly load the LightningModule itself from the checkpoint (as opposed to only `self.model`). The point is that if you save the checkpoint using the `Trainer` class, it also stores the optimizer state and other useful information in addition to the model `state_dict`. This is helpful in case you need to restart training from the last optimizer state:  [https://pytorch-lightning.readthedocs.io/en/latest/common/checkpointing_basic.html?highlight=checkpoint#save-a-checkpoint](https://pytorch-lightning.readthedocs.io/en/latest/common/checkpointing_basic.html?highlight=checkpoint#save-a-checkpoint).

Either design choice works, but the added benefit of being able to easily store the optimizer state can be useful in some cases. Not sure if this next example is helpful (ignore if this is the case), but in case it helps to see it used in a full project, here is how I set up training in one of my own projects: https://github.com/chiragraman/social-processes/blob/d6c2bd138ee59639d0d4f372e6d5bee251f4d60a/run/train_dataset.py#L88-L93

**Comment by gabinsane** [comment]
Closing this issue as the model loading method was moved back to the Trainer class in the current toolkit version
